nelmio_api_doc:
    documentation:
        info:
            title: 'My Application API'
            description: 'This API provides access to essential user and session management operations. It allows for user registration, login, profile updates, and more. Developed with a focus on security and ease of use, this documentation aims to provide all necessary information for you to integrate and effectively use our endpoints.'
            version: '1.0.0'
            termsOfService: 'http://example.com/terms/'
            contact:
                name: 'Developer Support'
                url: 'http://example.com/support'
                email: 'davidavirodrigues@gmail.com'
            license:
                name: 'MIT'
                url: 'http://opensource.org/licenses/MIT'
            # x-logo:
            #     url: 'http://example.com/logo.png'
            #     backgroundColor: '#444444'
            #     altText: 'My Application Logo'
        # securityDefinitions:
        #     bearerAuth:
        #         type: apiKey
        #         name: Authorization
        #         in: header
        #         description: 'To authenticate requests, you should use the JWT access token obtained after logging in. Enter the token in the authorization field as shown: "Bearer {token}".'
        externalDocs:
            description: 'Find more information about our API in the GitHub repository.'
            url: 'https://github.com/KingDev-code/Trackwise-API-PHP.git'
        servers:
            - url: 'http://127.0.0.1:8000'
              description: 'Staging server'
            - url: 'https://api.example.com'
              description: 'Production server (example)'
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
    areas:
        path_patterns:
            - ^/api
            - ^/register
            - ^/logout