controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

nelmio_api_doc:
  path: /
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

security_logout:
    path: /logout
    methods: GET
    defaults: { _controller: 'security.route_loader.logout' }